import type { Metadata } from "next";
import { SharedGenerationView } from "./SharedGenerationView";

interface Props {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  return {
    title: `NeuroUI Generation · ${id}`,
    description: "AI-generated React UI component — built with NeuroUI powered by the Cursor SDK.",
    openGraph: {
      title: "NeuroUI — AI-Generated UI",
      description: "See this AI-generated React component, built in seconds from a plain English description.",
      images: [{ url: "/og-image.png", width: 1200, height: 630 }],
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: "NeuroUI — AI-Generated UI",
      description: "React UI generated by 6 AI agents collaborating via the Cursor SDK.",
      images: ["/og-image.png"],
    },
  };
}

export default async function SharedPage({ params }: Props) {
  const { id } = await params;
  return <SharedGenerationView id={id} />;
}
