import JSZip from "jszip";
import type { CodeFile } from "../components/CodeView";

const PACKAGE_JSON = JSON.stringify(
  {
    name: "neuroui-export",
    version: "1.0.0",
    private: true,
    scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1",
      recharts: "^2.13.3",
      "lucide-react": "^0.460.0",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.3.1",
      autoprefixer: "^10.4.20",
      postcss: "^8.5.1",
      tailwindcss: "^3.4.17",
      typescript: "^5.7.3",
      vite: "^6.0.5",
    },
  },
  null,
  2
);

const TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: { extend: {} },
  plugins: [],
};
`;

const INDEX_HTML = `<!doctype html>
<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NeuroUI Export</title>
  </head>
  <body class="bg-[#0f0f0f]">
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

const MAIN_TSX = `import React from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App";

createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

const INDEX_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

html, body, #root { height: 100%; }
body { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; }
`;

const VITE_CONFIG = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({ plugins: [react()] });
`;

const POSTCSS_CONFIG = `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;

const README = `# NeuroUI Export

This component was generated by [NeuroUI](https://neuroui.vercel.app) — powered by 6 AI agents built on the Cursor SDK.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:5173 to view the component.

## Stack

- React 18 + TypeScript
- Tailwind CSS
- Recharts
- Lucide React
- Vite
`;

export async function downloadAsZip(files: CodeFile[], prompt: string): Promise<void> {
  const zip = new JSZip();

  zip.file("package.json", PACKAGE_JSON);
  zip.file("tailwind.config.js", TAILWIND_CONFIG);
  zip.file("index.html", INDEX_HTML);
  zip.file("vite.config.ts", VITE_CONFIG);
  zip.file("postcss.config.js", POSTCSS_CONFIG);
  zip.file("src/main.tsx", MAIN_TSX);
  zip.file("src/index.css", INDEX_CSS);
  zip.file("README.md", README);
  zip.file("PROMPT.md", `# Original Prompt\n\n${prompt}\n`);

  for (const f of files) {
    const relPath = f.path.startsWith("/") ? f.path.slice(1) : f.path;
    zip.file(relPath, f.contents);
  }

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "neuroui-component.zip";
  a.click();
  URL.revokeObjectURL(url);
}

export function openInStackBlitz(files: CodeFile[], prompt: string): void {
  const appFile = files.find(f => f.path.includes("App.tsx"));
  if (!appFile) return;

  const project = {
    title: "NeuroUI Export",
    description: prompt,
    template: "node",
    files: {
      "package.json": PACKAGE_JSON,
      "tailwind.config.js": TAILWIND_CONFIG,
      "index.html": INDEX_HTML,
      "vite.config.ts": VITE_CONFIG,
      "postcss.config.js": POSTCSS_CONFIG,
      "src/main.tsx": MAIN_TSX,
      "src/index.css": INDEX_CSS,
      ...Object.fromEntries(files.map(f => [f.path.startsWith("/") ? f.path.slice(1) : f.path, f.contents])),
    },
  };

  const form = document.createElement("form");
  form.method = "POST";
  form.action = "https://stackblitz.com/run";
  form.target = "_blank";

  const input = document.createElement("input");
  input.type = "hidden";
  input.name = "project";
  input.value = JSON.stringify(project);
  form.appendChild(input);

  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
}

export function openInCodeSandbox(files: CodeFile[]): void {
  const sandboxFiles: Record<string, { content: string }> = {
    "package.json": { content: PACKAGE_JSON },
    "tailwind.config.js": { content: TAILWIND_CONFIG },
    "index.html": { content: INDEX_HTML },
    "vite.config.ts": { content: VITE_CONFIG },
    "postcss.config.js": { content: POSTCSS_CONFIG },
    "src/main.tsx": { content: MAIN_TSX },
    "src/index.css": { content: INDEX_CSS },
  };
  for (const f of files) {
    const p = f.path.startsWith("/") ? f.path.slice(1) : f.path;
    sandboxFiles[p] = { content: f.contents };
  }

  const encoded = btoa(unescape(encodeURIComponent(JSON.stringify({ files: sandboxFiles }))));
  window.open(`https://codesandbox.io/api/v1/sandboxes/define?parameters=${encoded}&embed=1`, "_blank");
}
